### ISSUE TITLE
Grant BigQuery roles when can-compute/can-notebook is given to a user

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#202] opened 2018-05-29 22:05 UTC
We currently have a Orch endpoint which grants Google IAM roles (e.g. bigquery.jobUser) to a given user. It must be called by a project owner. However we'd like to automatically grant BQ roles when a user is given "can-notebook" permission.

This will most likely involve a change to Rawls UserService.

**Comment by rtitle** [comment] 2018-06-21 19:57
@bradtaylor @dmohs it seems like this is a dupe of this Leo ticket, correct? https://github.com/DataBiosphere/leonardo/issues/344

It seems there is a PR for this, so I can link it from the Leo ticket and close it as a dupe.

**Closed** 2018-06-22 20:46 UTC
