### ISSUE TITLE
Can't uncheck all in data tab

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#1041] opened 2019-01-09 20:54 UTC
When all entities of a type are selected (i.e. the checkbox column header is checked), clicking the header checkbox again should unselect all, just like clicking the arrow and selecting 'none'.

**Comment by elizzhao** [comment] 2019-02-06 18:48
was this fixed by #1134 ?

**Comment by bradtaylor** [comment] 2019-02-14 08:49
Closing as I cannot reproduce

**Closed by bradtaylor** 2019-02-14 08:49 UTC
