### ISSUE TITLE
Perform the following update to the Terra TOS 

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1177] opened 2019-02-11 22:01 UTC
Per @davidbernick. Add the following text:

"You must conduct only authorized business on the system.

Your level of access to systems and networks owned by Broad Institute is limited to ensure your access is no more than necessary to perform your legitimate tasks or assigned duties. If you believe you are being granted access that you should not have, you must immediately notify the Broad Institute Operations Center infosec@broadinstitute.org.

You must maintain the confidentiality of your authentication credentials such as your password. Do not reveal your authentication credentials to anyone; a Broad Institute employee should never ask you to reveal them.

You must follow proper logon/logoff procedures. You must manually logon to your session; do not store you password locally on your system or utilize any automated logon capabilities. You must promptly logoff when session access is no longer needed. If a logoff function is unavailable, you must close your browser. Never leave your computer unattended while logged into the system.

You must report all security incidents or suspected incidents (e.g., lost passwords, improper or suspicious acts) related to Broad Institute systems and networks to the Broad Institute Operations Center infosec@broadinstitute.org.

You must not establish any unauthorized interfaces between systems, networks, and applications owned by Broad Institute.

Your access to systems and networks owned by Broad Institute is governed by, and subject to, all Federal laws, including, but not limited to, the Privacy Act, 5 U.S.C. 552a, if the applicable Broad Institute system maintains individual Privacy Act information. Your access to Broad Institute systems constitutes your consent to the retrieval and disclosure of the information within the scope of your authorized access, subject to the Privacy Act, and applicable State and Federal laws.

You must safeguard system resources against waste, loss, abuse, unauthorized use or disclosure, and misappropriation.

You must not process U.S. classified national security information on the system.

You must not browse, search or reveal information hosted by Broad Institute except in accordance with that which is required to perform your legitimate tasks or assigned duties. 

You must not retrieve information, or in any other way disclose information, for someone who does not have authority to access that information.

You agree to contact the Broad Institute Chief Information Security Officer or the Broad Institute Operations Center (infosec@broadinstitute.org) if you do not understand any of these rules."

**Comment by katevoss** [comment] 2019-02-11 22:21
@davidbernick should this section go under [`By accessing and using Terra, you agree that you will:`](https://github.com/DataBiosphere/saturn-ui/blob/dev/src/pages/TermsOfService.js#L33)? Some of the existing information is a close duplicate of the new language provided by Brad. Should I replace that section with the exact wording from Brad? Or this update in addition to what exists in the TOS?

**Comment by davidbernick** [comment] 2019-02-11 22:23
Great question! Can you do your best to de-dupe the language and just add
what you think is not duplicative? Best judgment is fine!

**Closed** 2019-02-19 14:44 UTC
Labels: Compliance
