### ISSUE TITLE
Make cluster upgrades less inconvenient for users

### ISSUE THREAD

**Issue by panentheos** [DataBiosphere/saturn-ui#727] opened 2018-10-04 14:29 UTC
This came from a conversation with a user, who is frustrated at having to 1. wait for cluster rebuild, and 2. re-upload files and such whenever we update the cluster runtime. We should consider options for making this less of a burden. A few ideas:

* Could we rebuild the cluster before the user is logged in? Would require a back-end, and do we even have sufficient auth to do that?
* We talked about delocalizing the user's home directory. Would this solve the issue? What if it's very large?
* Could we allow upgrading the runtime scripts without rebuilding the cluster? E.g. push new scripts to existing clusters, or do something fancy with NFS so they could be updated from a central location.

**Comment by bradtaylor** [comment] 2018-10-04 16:17
Thanks for putting in this ticket! I've been working with some other users who felt this pain as well. There's a larger conversation that just started that includes this among a number of other pain points. I've got several docs to share- please slack me.

I put a meeting on your calendar for later today. We can talk about this then among other issues.

I think there are actually two pieces here:
1) Persisting state through cluster alterations
2) Removing the wait time we push cluster updates (ie rebuild the cluster before the user is logged in)

**Comment by bradtaylor** [comment] 2018-10-15 16:00
Represented both pieces of functionality as their own tickets, #762  and #763 
Closing this as a duplicate of those issues.

**Closed by bradtaylor** 2018-10-15 16:00 UTC
