### ISSUE TITLE
App crashes immediately in Firefox

### ISSUE THREAD

**Issue by aednichols** [DataBiosphere/saturn-ui#944] opened 2018-12-04 18:47 UTC
Firefox 60.3.0esr, macOS 10.13.6

Opening the side menu to sign in crashes the app.

Ad blocker is disabled.

<img width="1091" alt="screen shot 2018-12-04 at 1 42 46 pm" src="https://user-images.githubusercontent.com/1087943/49465085-ad6f3100-f7ca-11e8-990c-4d1f523b8cfe.png">

**Comment by aednichols** [comment] 2018-12-04 19:15
Yep, understood. Just wanted to get this on the radar because web apps should be at least moderately functional in every major browser.

**Comment by kleighwe** [comment] 2018-12-10 18:42
Notes from Refinement: 

- Give this ~15 minutes to look into, but don't spend too much time on it. 
- We should collect analytics on how many people run into this.

**Comment by aednichols** [comment] 2018-12-10 18:48
FWIW when I investigated myself I did not see any AJAX requests being made around the crash, so I'm not sure this would show up in any analytics without extra engineering

**Comment by panentheos** [comment] 2018-12-10 20:08
I was unable to reproduce this on the same FF version. The app loads normally and I am able to log in. Closing this for now, but we'll keep an eye out for additional reports. Thanks!

**Closed by panentheos** 2018-12-10 20:08 UTC
Labels: Spike, User-submitted, bug

**Comment by zarsky-broad** [comment] 2018-12-13 22:23
@aednichols I'd be suspicious of some overzealous content blocking, if you perhaps have changed some settings. It looks like the Google login library isn't being allowed to load, which we've only seen before with *really* overprotective content blockers and privacy plugins.

**Comment by aednichols** [comment] 2018-12-13 22:56
Good call, this was indeed a self-inflicted breakage.

Changing the blocklist from strict (_"Some websites may not function properly"_!) to recommended fixes the issue.

![screen shot 2018-12-13 at 5 51 57 pm](https://user-images.githubusercontent.com/1087943/49972488-d5177500-feff-11e8-827b-ad9886d383ff.png)

FWIW this is the first site that has required me to change this setting, but I agree there's nothing wrong with your app.
