### ISSUE TITLE
Registration email should say "Welcome to Terra", not FireCloud

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1271] opened 2019-03-10 21:49 UTC
I just registered an account through Terra and received an email:

> Subject: FireCloud Account Activation
> 
> Welcome to FireCloud!
> <etc>
 
Presumably all of this will be changing by May 1, but it will be a very nice milestone and element of our new user experience to be greeted from Terra and the Terra team.

**Comment by katevoss** [comment] 2019-03-11 13:52
I think this is a dupe of #801 fyi

**Comment by mbookman** [comment] 2019-03-12 03:36
Thanks @katevoss. Definitely in a similar vein.

**Comment by katevoss** [comment] 2019-03-13 13:37
I'm going to close this issue in favor of tracking work on the original issue. The changes will happen at the same time.

**Closed by katevoss** 2019-03-13 13:37 UTC

**Comment by bradtaylor** [comment] 2019-03-22 16:38
@katevoss if you are closing an issue as a duplicate, please apply the duplciate label
