### ISSUE TITLE
Add clusters to billing

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#1088] opened 2019-01-17 20:35 UTC
Add cluster management to the billing page.
Per project, users should see the status of their cluster, be able to create/resize it, be able to pause/destroy it. They should also see the cost.

**Comment by bradtaylor** [comment] 2019-02-14 07:45
Closing as a duplicate of #538

**Closed by bradtaylor** 2019-02-14 07:45 UTC
