### ISSUE TITLE
Need error for when user tries to upload non-ipynb file

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#550] opened 2018-08-22 19:44 UTC
When I drag and drop a file that does not have a ipynb extension, I don't get an error message. I expect an error telling me that I can only upload that file type.

**Comment by MattPutnam** [comment] 2018-08-23 19:39
@katevoss is this a duplicate of #478?

**Comment by katevoss** [comment] 2018-08-24 16:59
There is one other usage of `dropzone` in Saturn, where a user can click and drag a JSON file to upload their inputs. 
<img width="1263" alt="screen shot 2018-08-24 at 12 54 52 pm" src="https://user-images.githubusercontent.com/2395211/44597359-5a361d00-a79d-11e8-9174-b17364f54f42.png">

The user will face the same issue where if they try to upload a file with an extension that is not .json, there will be no error message and the upload will fail. I'll fix this at the same time if I can with a reasonable amount of effort.

**Closed** 2018-08-27 20:38 UTC
Labels: bug
